name: Shop
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.5
  http: ^1.1.0
  line_icons: ^2.0.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  image_picker: ^1.1.2
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# ✅ بخش تنظیمات Splash Screen باید اینجا باشد و نه داخل flutter:
flutter_native_splash:
  color: "#ffffff" # رنگ پس‌زمینه
  image: assets/images/logo.png # مسیر تصویر لوگو
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/
    - assets/images/slider/
    - assets/images/blog/
    - assets/images/category/
    - assets/images/products/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/static/Roboto_Condensed-Regular.ttf
        - asset: assets/fonts/Roboto/static/Roboto_Condensed-Bold.ttf
          weight: 700
    - family: YekanBakh
      fonts:
        - asset: assets/fonts/YekanBakh_Thin.ttf
          weight: 100
        - asset: assets/fonts/YekanBakh_Light.ttf
          weight: 200
        - asset: assets/fonts/YekanBakh_Regular.ttf
          weight: 300
        - asset: assets/fonts/YekanBakh_Medium.ttf
          weight: 400
        - asset: assets/fonts/YekanBakh_Fat.ttf
          weight: 500
        - asset: assets/fonts/YekanBakh_Bold.ttf
          weight: 600
        - asset: assets/fonts/YekanBakh_Heavy.ttf
          weight: 700
